project/client/forms.py
# project/client/forms.py


from flask_wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired, Email, Length, URL


class AddClientForm(Form):
    first_name = StringField(
        'First Name', validators=[DataRequired(), Length(min=3)])
    last_name = StringField(
        'Last Name', validators=[DataRequired(), Length(min=3)])
    email = StringField(
        'Email Address', validators=[DataRequired(), Email(), Length(min=7)])
    company = StringField(
        'Company Name', validators=[DataRequired(), Length(min=3)])
    website = StringField('Website', validators=[URL()])
    telephone = StringField(
        "Telephone (10-digit)", validators=[Length(min=10, max=10)])
    street = StringField('Street Address')
    city = StringField('City')
    state = StringField('State', validators=[Length(min=2)])
    postal_code = StringField('Postal Code', validators=[Length(min=5)])
    country = StringField('County', validators=[Length(min=2)])

project/invoice/forms.py
# project/invoice/forms.py


import datetime

from flask_wtf import Form
from wtforms import FloatField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired


class AddInvoiceForm(Form):
    client = SelectField('Client', coerce=int)
    total_price = FloatField('Total Price (USD)', validators=[DataRequired()])
    invoice_date = DateField('Invoice Date', default=datetime.datetime.now())
    due_date = DateField('Due Date')

project/user/forms.py
# project/user/forms.py


from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email


class LoginForm(Form):
    email = TextField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])

app/views/projects.py
from flask import render_template, session, redirect, url_for, request, flash
from app import app, db
from app.models import Project, Client

@app.route('/projects')
def projects():
	if session.get('username'):
		projects = Project.query.order_by('name')
		return render_template('projects/projects.html',
			title = 'projects',
			projects = projects)
	else:
		return redirect(url_for('login'))

@app.route('/projects/<int:project_id>')
def view_project(project_id):
	if session.get('username'):
		project = Project.query.get(project_id)
		return render_template('projects/view.html',
			title = project.name,
			project = project)
	else:
		return redirect(url_for('login'))

@app.route('/projects/create', methods = ['GET', 'POST'])
def create_project():
	if session.get('username'):
		clients = Client.query.order_by('name')
		if request.method == 'POST':
			client = Client.query.get(request.form['client'])
			project = Project(
				name = request.form['name'],
				description = request.form['description'],
				status = request.form['status'],
#				project_start = request.form['project_start'],
#				project_end = request.form['project_end'],
				hourly_rate = request.form['hourly_rate'],
				quote = request.form['quote'],
				notes = request.form['notes'],
				client = client)
			db.session.add(project)
			db.session.commit()
			flash("Project '%s' was added." % project.name)
			return redirect(url_for('projects'))
		return render_template('projects/create.html',
			title = 'Add a New Project',
			clients = clients)
	else:
		return redirect(url_for('login'))

@app.route('/projects/edit/<int:project_id>', methods = ['GET', 'POST'])
def edit_project(project_id):
	if session.get('username'):
		project = Project.query.get(project_id)
		clients = Client.query.order_by('name')
		if request.method == 'POST':
			client = Client.query.get(request.form['client'])
			project.name = request.form['name']
			project.description = request.form['description']
			project.status = request.form['status']
#			project.project_start = request.form['project_start']
#			project.project_end = request.form['project_end']
			project.hourly_rate = request.form['hourly_rate']
			project.quote = request.form['quote']
			project.notes = request.form['notes']
			project.client = client
			db.session.add(project)
			db.session.commit()
			flash("Project '%s' has been updated." % project.name)
			return redirect(url_for('projects'))
		return render_template('projects/edit.html',
			title = 'Edit %s' % project.name,
			project = project,
			clients = clients)
	else:
		return redirect(url_for('login'))

@app.route('/projects/delete/<int:project_id>', methods = ['GET', 'POST'])
def delete_project(project_id):
	if session.get('username'):
		project = Project.query.get(project_id)
		if request.method == 'POST':
			db.session.delete(project)
			db.session.commit()
			flash("Project '%s' has been deleted." % project.name)
			return redirect(url_for('projects'))
		return render_template('projects/delete.html',
			title = 'Delete %s' % project.name,
			project = project)
	else:
		return redirect(url_for('login'))

project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask_mail import Mail
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy


################
#### config ####
################

app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])


####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)


###################
### blueprints ####
###################

from project.client.views import client_blueprint
from project.user.views import user_blueprint
from project.main.views import main_blueprint
from project.invoice.views import invoice_blueprint
app.register_blueprint(client_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(main_blueprint)
app.register_blueprint(invoice_blueprint)


###################
### flask-login ####
###################

from models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = 'danger'


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/client/__init__.py
# project/client/__init__.py

project/client/views.py
# project/client/views.py


#################
#### imports ####
#################

import datetime

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request, abort
from flask.ext.login import login_required

from project import db
from project.models import Client
from project.client.forms import AddClientForm


################
#### config ####
################

client_blueprint = Blueprint('client', __name__,)


################
#### routes ####
################

@client_blueprint.route('/clients')
@login_required
def clients():
    clients = Client.query.order_by('last_name').all()
    return render_template(
        'clients/clients.html',
        title='Clients',
        clients=clients
    )


@client_blueprint.route('/clients/<int:client_id>')
@login_required
def view_client(client_id):
    client = Client.query.get(client_id)
    if client:
        invoices = client.invoices.all()
        return render_template(
            'clients/view.html',
            title=client.company,
            client=client,
            invoices=invoices
        )
    else:
        abort(404)


@client_blueprint.route('/clients/create', methods=['GET', 'POST'])
@login_required
def create_client():
    form = AddClientForm()
    if form.validate_on_submit():
        client = Client(
            first_name=request.form['first_name'],
            last_name=request.form['last_name'],
            email=request.form['email'],
            company=request.form['company'],
            website=request.form['website'],
            telephone=request.form['telephone'],
            street=request.form['street'],
            city=request.form['city'],
            state=request.form['state'],
            postal_code=request.form['postal_code'],
            country=request.form['country'],
            date_created=datetime.datetime.now()
        )
        db.session.add(client)
        db.session.commit()
        flash("Client '{0}' was added.".format(client.company), 'success')
        return redirect(url_for('client.clients'))
    return render_template('clients/create.html', title="Add Client", form=form)


@client_blueprint.route(
    '/clients/edit/<int:client_id>', methods=['GET', 'POST'])
@login_required
def edit_client(client_id):
    form = AddClientForm()
    client = Client.query.get(client_id)
    if form.validate_on_submit():
        client.first_name = request.form['first_name']
        client.last_name = request.form['last_name']
        client.email = request.form['email']
        client.company = request.form['company']
        client.website = request.form['website']
        client.telephone = request.form['telephone']
        client.street = request.form['street']
        client.city = request.form['city']
        client.state = request.form['state']
        client.postal_code = request.form['postal_code']
        client.country = request.form['country']
        db.session.add(client)
        db.session.commit()
        flash("Client '{0}' was updated.".format(client.company), 'success')
        return redirect(url_for('client.clients'))
    return render_template(
        'clients/edit.html',
        title='Edit {0}'.format(client.company),
        client=client,
        form=form
    )


@client_blueprint.route(
    '/clients/delete/<int:client_id>', methods=['GET', 'POST'])
@login_required
def delete_client(client_id):
    client = Client.query.get(client_id)
    if request.method == 'POST':
        db.session.delete(client)
        db.session.commit()
        flash("Client '{0}' was deleted.".format(client.company), 'success')
        return redirect(url_for('client.clients'))
    return render_template(
        'clients/delete.html',
        title='Delete {0}'.format(client.company),
        client=client
    )

project/invoice/__init__.py
# project/invoice/__init__.py

project/invoice/views.py
# project/invoice/views.py


#################
#### imports ####
#################

import datetime

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_required

from project import db
from project.models import Invoice, Client
from project.invoice.forms import AddInvoiceForm


################
#### config ####
################

invoice_blueprint = Blueprint('invoice', __name__,)


################
#### routes ####
################


@invoice_blueprint.route('/invoices')
@login_required
def invoices():
    invoices = Invoice.query.order_by('due_date').all()
    return render_template(
        'invoices/invoices.html',
        title='Invoices',
        invoices=invoices
    )


@invoice_blueprint.route('/invoices/create', methods=['GET', 'POST'])
@login_required
def create_invoice():
    form = AddInvoiceForm()
    categories = [(c.id, c.company) for c in Client.query.order_by('company')]
    form.client.choices = categories
    if form.validate_on_submit():
        client = Client.query.get(request.form['client'])
        invoice = Invoice(
            paid=0,
            invoice_date=datetime.datetime.strptime(
                request.form['invoice_date'], '%Y-%m-%d'),
            due_date=datetime.datetime.now(),
            total_price=request.form['total_price'],
            client=client
        )
        db.session.add(invoice)
        db.session.commit()
        flash("Invoice #'{0}' was added for '{1}'.".format(
            invoice.id, client.company),  'success')
        return redirect(url_for('invoice.invoices'))
    return render_template(
        'invoices/create.html',
        title='Add New Invoice',
        form=form
    )


@invoice_blueprint.route(
    '/invoices/edit/<int:invoice_id>', methods=['GET', 'POST'])
@login_required
def edit_invoice(invoice_id):
    invoice = Invoice.query.get(invoice_id)
    clients = Client.query.order_by('name')
    if request.method == 'POST':
        client = Client.query.get(request.form['client'])
        invoice.currency = request.form['currency']
        invoice.status = request.form['status']
        invoice.notes = request.form['notes']
        invoice.payment = request.form['payment']
        invoice.internal_notes = request.form['internal_notes']
        invoice.client = client
        db.session.add(invoice)
        db.session.commit()
        flash("Invoice '{0}' has been updated.".format(invoice.name))
        return redirect(url_for('invoice.invoices'))
    return render_template(
        'invoices/edit.html',
        title='Edit Invoice {0}'.format("test"),
        invoice=invoice,
        clients=clients,
    )


@invoice_blueprint.route(
    '/invoices/delete/<int:invoice_id>', methods=['GET', 'POST'])
@login_required
def delete_invoice(invoice_id):
    invoice = Invoice.query.get(invoice_id)
    if request.method == 'POST':
        db.session.delete(invoice)
        db.session.commit()
        flash("Invoice '{0}' has been deleted.".format(invoice.name))
        return redirect(url_for('invoice.invoices'))
    return render_template(
        'invoices/delete.html',
        title='Delete Invoice {0}'.format(invoice.name),
        invoice=invoice
    )

project/main/__init__.py
# project/main/__init__.py

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from calendar import Calendar
from datetime import date

from flask import render_template, Blueprint
from flask.ext.login import login_required


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/')
def home():
    return render_template('main/home.html', title="Welcome")


@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    cal = Calendar(0)
    year = date.today().year
    month = date.today().month
    cal_list = [cal.monthdatescalendar(year, month)]
    return render_template(
        'main/dashboard.html',
        title='Dashboard',
        year=year,
        this_month=month,
        calendar=cal_list
    )

project/user/__init__.py
# project/user/__init__.py

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, login_required

from project import bcrypt
from project.models import User
from project.user.forms import LoginForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))

project/templates/_base.html
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Cabinet | {{ title }}</title>
    <!-- meta -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.1/yeti/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet" media="screen">
    {% block css %}{% endblock %}
  </head>

  <body>

    {% include 'header.html' %}

    <div class="site-content">
      <div class="container">

        <!-- messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <br>
        <div class="row">
          <div class="col-md-12">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
              <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
             {{message}}
            </div>
            {% endfor %}
          </div>
        </div>
        {% endif %}
        {% endwith %}


        <!-- child template -->
        {% block content %}{% endblock %}

        <br>

        <!-- errors -->
        {% if error %}
          <p class="error"><strong>Error:</strong> {{ error }}</p>
        {% endif %}

      </div>
    </div>

    {% include 'footer.html' %}

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js" type="text/javascript"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{url_for('static', filename='js/main.js')}}" type="text/javascript"></script>
    {% block js %}{% endblock %}

  </body>
</html>

project/templates/_footer.html
<div class="site-footer">
	<div class="container">
		<p>App code on <a href="https://github.com/soniacs/cabinet">Github</a>.</p>
	</div>
</div>

project/templates/base.html
<!doctype html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,300,600,700' rel='stylesheet' type='text/css'>
	<title>{{ title }} - Cabinet</title>
	{% block css %}
		{% assets 'css' %}
			<link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}">
		{% endassets %}
	{% endblock %}
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	{% block head_js %}
	{% endblock %}
</head>
<body>
	{% block header %}
		{% include '_header.html' %}
	{% endblock %}
	<div class="site-content">
		<div class="container">
			{% block content %}{% endblock %}
		</div>
	</div>
	{% block footer %}
		{% include '_footer.html' %}
	{% endblock %}
	{% block footer_js %}
		{% assets "js" %}
			<script type="text/javascript" src="{{ ASSET_URL }}"></script>
		{% endassets %}
	{% endblock %}
</body>
</html>

project/templates/footer.html
<div class="site-footer">
	<div class="container">
		<p>App code on <a href="https://github.com/soniacs/cabinet">Github</a>.</p>
	</div>
</div>

project/templates/header.html
<header class="site-header">
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        {% if current_user.is_authenticated() %}
          <a class="navbar-brand" href="{{ url_for('main.dashboard') }}">
            <span class="glyphicon glyphicon-envelope" style="font-size: 15px;"></span>&nbsp;Cabinet
          </a>
        {% else %}
          <a class="navbar-brand" href="{{ url_for('main.home') }}">
            <span class="glyphicon glyphicon-envelope" style="font-size: 15px;"></span>&nbsp;Cabinet
          </a>
        {% endif %}
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          {% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('main.dashboard') }}">Dashboard</a></li>
            <li><a href="{{ url_for('client.clients') }}">Clients</a></li>
            <li><a href="{{ url_for('invoice.invoices') }}">Invoices</a></li>
          {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
          {% else %}
            <li><a href="{{ url_for('user.login') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;Login</a></li>
          {% endif %}
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
</header>

project/templates/index.html
{% extends '_base.html' %}
{% block content %}
	<div class="calendar">
		{% for month in calendar %}
<!--			<h2 class="{% if loop.index == this_month %}current-{% endif %}month">{{ ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][loop.index0] }} {{ year }}</h2> -->
			<h2 class="{% if loop.index == this_month %}current-{% endif %}month">{{ [0, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][this_month] }} {{ year }}</h2>
			<table class="{% if loop.index == this_month %}current-{% endif %}month">
				<tr>
					<th>MON</th>
					<th>TUE</th>
					<th>WED</th>
					<th>THU</th>
					<th>FRI</th>
					<th>SAT</th>
					<th>SUN</th>
				</tr>
			{% for week in month %}
				<tr>
				{% for date in week %}
					<td>
						<p class="day">{{ date.day }}</p>
					</td>
				{% endfor %}
				</tr>
			{% endfor %}
			</table>
		{% endfor %}
	</div>

	<ul class="messages">
	{% for i in range(0,3) %}<li class="project">
		<h3>Project Name</h3>
		<h4>Client Name</h4>
		<p class="msg-categories">
			<span class="msg-todo">Todo</span>
			<span class="msg-tasks">Tasks</span>
			<span class="msg-invoices">Invoices</span>
		</p>
	</li>{% endfor %}
	</ul>
{% endblock %}