app/views/clients.py
from flask import render_template, session, redirect, url_for, request, flash
from app import app, db
from app.models import Client

@app.route('/clients')
def clients():
	if session.get('username'):
		clients = Client.query.order_by('name')
		return render_template('clients/clients.html',
			title = 'Clients',
			clients = clients)
	else:
		return redirect(url_for('login'))

@app.route('/clients/<int:client_id>')
def view_client(client_id):
	if session.get('username'):
		client = Client.query.get(client_id)
		projects = client.projects.all()
		invoices = client.invoices.all()
		return render_template('clients/view.html',
			title = client.name,
			client = client,
			projects = projects,
			invoices = invoices)
	else:
		return redirect(url_for('login'))

@app.route('/clients/create', methods = ['GET', 'POST'])
def create_client():
	if session.get('username'):
		if request.method == 'POST':
			client = Client(
				name = request.form['name'],
				company = request.form['company'],
				website = request.form['website'],
				twitter = request.form['twitter'],
				email = request.form['email'],
				telephone = request.form['telephone'],
				skype = request.form['skype'],
				street = request.form['street'],
				street_2 = request.form['street_2'],
				city = request.form['city'],
				state = request.form['state'],
				postcode = request.form['postcode'],
				country = request.form['country'],
				notes = request.form['notes'])
			db.session.add(client)
			db.session.commit()
			flash("Client '%s' was added." % client.name)
			return redirect(url_for('clients'))
		return render_template('clients/create.html',
			title = 'Add a New Client')
	else:
		return redirect(url_for('login'))

@app.route('/clients/edit/<int:client_id>', methods = ['GET', 'POST'])
def edit_client(client_id):
	if session.get('username'):
		client = Client.query.get(client_id)
		if request.method == 'POST':
			client.name = request.form['name']
			client.company = request.form['company']
			client.website = request.form['website']
			client.twitter = request.form['twitter']
			client.email = request.form['email']
			client.telephone = request.form['telephone']
			client.skype = request.form['skype']
			client.street = request.form['street']
			client.street_2 = request.form['street_2']
			client.city = request.form['city']
			client.state = request.form['state']
			client.postcode = request.form['postcode']
			client.country = request.form['country']
			client.notes = request.form['notes']
			db.session.add(client)
			db.session.commit()
			flash("Client '%s' has been updated." % client.name)
			return redirect(url_for('clients'))
		return render_template('clients/edit.html',
			title = 'Edit %s' % client.name,
			client = client)
	else:
		return redirect(url_for('login'))

@app.route('/clients/delete/<int:client_id>', methods = ['GET', 'POST'])
def delete_client(client_id):
	if session.get('username'):
		client = Client.query.get(client_id)
		if request.method == 'POST':
			db.session.delete(client)
			db.session.commit()
			flash("Client '%s' has been deleted." % client.name)
			return redirect(url_for('clients'))
		return render_template('clients/delete.html',
			title = 'Delete %s' % client.name,
			client = client)
	else:
		return redirect(url_for('login'))

app/views/projects.py
from flask import render_template, session, redirect, url_for, request, flash
from app import app, db
from app.models import Project, Client

@app.route('/projects')
def projects():
	if session.get('username'):
		projects = Project.query.order_by('name')
		return render_template('projects/projects.html',
			title = 'projects',
			projects = projects)
	else:
		return redirect(url_for('login'))

@app.route('/projects/<int:project_id>')
def view_project(project_id):
	if session.get('username'):
		project = Project.query.get(project_id)
		return render_template('projects/view.html',
			title = project.name,
			project = project)
	else:
		return redirect(url_for('login'))

@app.route('/projects/create', methods = ['GET', 'POST'])
def create_project():
	if session.get('username'):
		clients = Client.query.order_by('name')
		if request.method == 'POST':
			client = Client.query.get(request.form['client'])
			project = Project(
				name = request.form['name'],
				description = request.form['description'],
				status = request.form['status'],
#				project_start = request.form['project_start'],
#				project_end = request.form['project_end'],
				hourly_rate = request.form['hourly_rate'],
				quote = request.form['quote'],
				notes = request.form['notes'],
				client = client)
			db.session.add(project)
			db.session.commit()
			flash("Project '%s' was added." % project.name)
			return redirect(url_for('projects'))
		return render_template('projects/create.html',
			title = 'Add a New Project',
			clients = clients)
	else:
		return redirect(url_for('login'))

@app.route('/projects/edit/<int:project_id>', methods = ['GET', 'POST'])
def edit_project(project_id):
	if session.get('username'):
		project = Project.query.get(project_id)
		clients = Client.query.order_by('name')
		if request.method == 'POST':
			client = Client.query.get(request.form['client'])
			project.name = request.form['name']
			project.description = request.form['description']
			project.status = request.form['status']
#			project.project_start = request.form['project_start']
#			project.project_end = request.form['project_end']
			project.hourly_rate = request.form['hourly_rate']
			project.quote = request.form['quote']
			project.notes = request.form['notes']
			project.client = client
			db.session.add(project)
			db.session.commit()
			flash("Project '%s' has been updated." % project.name)
			return redirect(url_for('projects'))
		return render_template('projects/edit.html',
			title = 'Edit %s' % project.name,
			project = project,
			clients = clients)
	else:
		return redirect(url_for('login'))

@app.route('/projects/delete/<int:project_id>', methods = ['GET', 'POST'])
def delete_project(project_id):
	if session.get('username'):
		project = Project.query.get(project_id)
		if request.method == 'POST':
			db.session.delete(project)
			db.session.commit()
			flash("Project '%s' has been deleted." % project.name)
			return redirect(url_for('projects'))
		return render_template('projects/delete.html',
			title = 'Delete %s' % project.name,
			project = project)
	else:
		return redirect(url_for('login'))

project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os

from flask import Flask, render_template
from flask.ext.login import LoginManager
from flask.ext.bcrypt import Bcrypt
from flask_mail import Mail
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask_bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy


################
#### config ####
################

app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])


####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
bootstrap = Bootstrap(app)
db = SQLAlchemy(app)


###################
### blueprints ####
###################

from project.client.views import client_blueprint
from project.user.views import user_blueprint
from project.main.views import main_blueprint
from project.invoice.views import invoice_blueprint
app.register_blueprint(client_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(main_blueprint)
app.register_blueprint(invoice_blueprint)


###################
### flask-login ####
###################

from models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = 'danger'


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


########################
#### error handlers ####
########################

@app.errorhandler(403)
def forbidden_page(error):
    return render_template("errors/403.html"), 403


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

project/client/__init__.py
# project/client/__init__.py

project/client/views.py
# project/client/views.py


#################
#### imports ####
#################

import datetime

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request, abort
from flask.ext.login import login_required

from project import db
from project.models import Client
from project.client.forms import AddClientForm


################
#### config ####
################

client_blueprint = Blueprint('client', __name__,)


################
#### routes ####
################

@client_blueprint.route('/clients')
@login_required
def clients():
    clients = Client.query.order_by('last_name').all()
    return render_template(
        'clients/clients.html',
        title='Clients',
        clients=clients
    )


@client_blueprint.route('/clients/<int:client_id>')
@login_required
def view_client(client_id):
    client = Client.query.get(client_id)
    if client:
        invoices = client.invoices.all()
        return render_template(
            'clients/view.html',
            title=client.company,
            client=client,
            invoices=invoices
        )
    else:
        abort(404)


@client_blueprint.route('/clients/create', methods=['GET', 'POST'])
@login_required
def create_client():
    form = AddClientForm()
    if form.validate_on_submit():
        client = Client(
            first_name=request.form['first_name'],
            last_name=request.form['last_name'],
            email=request.form['email'],
            company=request.form['company'],
            website=request.form['website'],
            telephone=request.form['telephone'],
            street=request.form['street'],
            city=request.form['city'],
            state=request.form['state'],
            postal_code=request.form['postal_code'],
            country=request.form['country'],
            date_created=datetime.datetime.now()
        )
        db.session.add(client)
        db.session.commit()
        flash("Client '{0}' was added.".format(client.company), 'success')
        return redirect(url_for('client.clients'))
    return render_template('clients/create.html', title="Add Client", form=form)


@client_blueprint.route(
    '/clients/edit/<int:client_id>', methods=['GET', 'POST'])
@login_required
def edit_client(client_id):
    form = AddClientForm()
    client = Client.query.get(client_id)
    if form.validate_on_submit():
        client.first_name = request.form['first_name']
        client.last_name = request.form['last_name']
        client.email = request.form['email']
        client.company = request.form['company']
        client.website = request.form['website']
        client.telephone = request.form['telephone']
        client.street = request.form['street']
        client.city = request.form['city']
        client.state = request.form['state']
        client.postal_code = request.form['postal_code']
        client.country = request.form['country']
        db.session.add(client)
        db.session.commit()
        flash("Client '{0}' was updated.".format(client.company), 'success')
        return redirect(url_for('client.clients'))
    return render_template(
        'clients/edit.html',
        title='Edit {0}'.format(client.company),
        client=client,
        form=form
    )


@client_blueprint.route(
    '/clients/delete/<int:client_id>', methods=['GET', 'POST'])
@login_required
def delete_client(client_id):
    client = Client.query.get(client_id)
    if request.method == 'POST':
        db.session.delete(client)
        db.session.commit()
        flash("Client '{0}' was deleted.".format(client.company), 'success')
        return redirect(url_for('client.clients'))
    return render_template(
        'clients/delete.html',
        title='Delete {0}'.format(client.company),
        client=client
    )

project/invoice/__init__.py
# project/invoice/__init__.py

project/invoice/views.py
# project/invoice/views.py


#################
#### imports ####
#################

import datetime

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_required

from project import db
from project.models import Invoice, Client
from project.invoice.forms import AddInvoiceForm


################
#### config ####
################

invoice_blueprint = Blueprint('invoice', __name__,)


################
#### routes ####
################


@invoice_blueprint.route('/invoices')
@login_required
def invoices():
    invoices = Invoice.query.order_by('due_date').all()
    return render_template(
        'invoices/invoices.html',
        title='Invoices',
        invoices=invoices
    )


@invoice_blueprint.route('/invoices/create', methods=['GET', 'POST'])
@login_required
def create_invoice():
    form = AddInvoiceForm()
    categories = [(c.id, c.company) for c in Client.query.order_by('company')]
    form.client.choices = categories
    if form.validate_on_submit():
        client = Client.query.get(request.form['client'])
        invoice = Invoice(
            paid=0,
            invoice_date=datetime.datetime.strptime(
                request.form['invoice_date'], '%Y-%m-%d'),
            due_date=datetime.datetime.now(),
            total_price=request.form['total_price'],
            client=client
        )
        db.session.add(invoice)
        db.session.commit()
        flash("Invoice #'{0}' was added for '{1}'.".format(
            invoice.id, client.company),  'success')
        return redirect(url_for('invoice.invoices'))
    return render_template(
        'invoices/create.html',
        title='Add New Invoice',
        form=form
    )


@invoice_blueprint.route(
    '/invoices/edit/<int:invoice_id>', methods=['GET', 'POST'])
@login_required
def edit_invoice(invoice_id):
    invoice = Invoice.query.get(invoice_id)
    clients = Client.query.order_by('name')
    if request.method == 'POST':
        client = Client.query.get(request.form['client'])
        invoice.currency = request.form['currency']
        invoice.status = request.form['status']
        invoice.notes = request.form['notes']
        invoice.payment = request.form['payment']
        invoice.internal_notes = request.form['internal_notes']
        invoice.client = client
        db.session.add(invoice)
        db.session.commit()
        flash("Invoice '{0}' has been updated.".format(invoice.name))
        return redirect(url_for('invoice.invoices'))
    return render_template(
        'invoices/edit.html',
        title='Edit Invoice {0}'.format("test"),
        invoice=invoice,
        clients=clients,
    )


@invoice_blueprint.route(
    '/invoices/delete/<int:invoice_id>', methods=['GET', 'POST'])
@login_required
def delete_invoice(invoice_id):
    invoice = Invoice.query.get(invoice_id)
    if request.method == 'POST':
        db.session.delete(invoice)
        db.session.commit()
        flash("Invoice '{0}' has been deleted.".format(invoice.name))
        return redirect(url_for('invoice.invoices'))
    return render_template(
        'invoices/delete.html',
        title='Delete Invoice {0}'.format(invoice.name),
        invoice=invoice
    )

project/main/__init__.py
# project/main/__init__.py

project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from calendar import Calendar
from datetime import date

from flask import render_template, Blueprint
from flask.ext.login import login_required


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################


@main_blueprint.route('/')
def home():
    return render_template('main/home.html', title="Welcome")


@main_blueprint.route('/dashboard')
@login_required
def dashboard():
    cal = Calendar(0)
    year = date.today().year
    month = date.today().month
    cal_list = [cal.monthdatescalendar(year, month)]
    return render_template(
        'main/dashboard.html',
        title='Dashboard',
        year=year,
        this_month=month,
        calendar=cal_list
    )

project/user/__init__.py
# project/user/__init__.py

project/user/views.py
# project/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request
from flask.ext.login import login_user, logout_user, login_required

from project import bcrypt
from project.models import User
from project.user.forms import LoginForm

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)


################
#### routes ####
################

@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))

project/templates/clients/clients.html
{% extends '_base.html' %}

{% block content %}

  <header class="content-header">
    <h1>Clients</h1>
  </header>

  <br><br>

  <a href="{{ url_for('client.create_client') }}" class="btn btn-success btn-xs">Add Client</a>

  <br><br>

  {% if clients %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Client ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Company</th>
          <th>Email Address</th>
          <th>Date Created</th>
          <th>Actions</th>
        <tr>
      </thead>
      <tbody>
        {% for client in clients %}
          <tr>
            <th>{{ client.id }}</th>
            <th>{{ client.first_name }}</th>
            <th>{{ client.last_name }}</th>
            <th>{{ client.company }}</th>
            <th><a href="mailto:{{ client.email }}" target="_top">{{ client.email }}</a></th>
            <th>{{ client.date_created.strftime('%m-%d-%Y') }}</th>
            <th>
              <a href="{{ url_for('client.view_client', client_id = client.id) }}">View</a> |
              <a href="{{ url_for('client.edit_client', client_id = client.id) }}">Edit</a> |
              <a href="{{ url_for('client.delete_client', client_id = client.id) }}">Delete</a>
            </th>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>You haven't created any clients yet.</p>
  {% endif %}

{% endblock content %}

project/templates/clients/create.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Clients / <em>Add Client</em></h1>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}

    <div class="col-lg-12 col-sm-12">

      <div class="col-lg-4 col-sm-4">
        <h3>Contact</h3>
        <hr><br>
        {{ wtf.form_field(form.first_name) }}
        {{ wtf.form_field(form.last_name) }}
        {{ wtf.form_field(form.email) }}
        {{ wtf.form_field(form.telephone) }}
      </div>

      <div class="col-lg-4 col-sm-4">
        <h3>Organization</h3>
        <hr><br>
        {{ wtf.form_field(form.company) }}
        {{ wtf.form_field(form.website) }}
      </div>

      <div class="col-lg-4 col-sm-4">
        <h3>Address</h3>
        <hr><br>
        {{ wtf.form_field(form.street) }}
        {{ wtf.form_field(form.city) }}
        {{ wtf.form_field(form.state) }}
        {{ wtf.form_field(form.postal_code) }}
        {{ wtf.form_field(form.country) }}
      </div>

    </div>

    <div class="col-lg-12 col-sm-12">
      <button class="btn btn-success btn-lg" type="submit">Add Client</button>
      <a href="{{ url_for('client.clients') }}" class="btn btn-default btn-lg">Cancel</a>
    </div>

  </form>


{% endblock content %}

project/templates/clients/delete.html
{% extends '_base.html' %}

{% block content %}

  <header class="content-header">
    <h1>Clients / <em>Delete Client</em></h1>
  </header>

  <br>

  <form action="" method="post" name="delete-client">
    <p>Are you sure you want to delete client <em>{{ client.company }}</em>?</p>
    <input type="hidden" name="delete">
    <button class="btn btn-success" type="submit">Delete</button>
    <a href="{{ url_for('client.clients') }}" class="btn btn-default">Cancel</a>
  </form>

{% endblock content %}

project/templates/clients/edit.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Clients / <em>Edit Client</em></h1>
  </header>

  <br>

  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      <h3>Contact</h3>
      <hr><br>
      {{ wtf.form_field(form.first_name, value=client.first_name) }}
      {{ wtf.form_field(form.last_name, value=client.last_name) }}
      {{ wtf.form_field(form.email, value=client.email) }}
      {{ wtf.form_field(form.telephone, value=client.telephone) }}

    </div>

    <div class="col-lg-4 col-sm-4">

      <h3>Organization</h3>
      <hr><br>

      {{ wtf.form_field(form.company, value=client.company) }}
      {{ wtf.form_field(form.website, value=client.website) }}

    </div>

    <div class="col-lg-4 col-sm-4">

      <h3>Address</h3>
      <hr><br>

      {{ wtf.form_field(form.street, value=client.street) }}
      {{ wtf.form_field(form.city, value=client.city) }}
      {{ wtf.form_field(form.state, value=client.state) }}
      {{ wtf.form_field(form.postal_code, value=client.postal_code) }}
      {{ wtf.form_field(form.country, value=client.country) }}

    </div>

    <button class="btn btn-success btn-lg" type="submit">Update Client</button>
    <a href="{{ url_for('client.clients') }}" class="btn btn-default btn-lg">Cancel</a>

  </form>

{% endblock content %}

project/templates/clients/view.html
{% extends '_base.html' %}

{% block content %}

  <header class="content-header">
    <h1>Clients / <em>{{ client.company }}</em></h1>
  </header>

  <br>

  <div class="col-lg-3 col-sm-3">

    <h3>Contact</h3>
    <hr>
    <p>
      <strong>{{ client.first_name }} {{client.last_name}}</strong><br>
      {{ client.email }}<br>
      {{ client.telephone }}
    </p>

  </div>

  <div class="col-lg-3 col-sm-3">

    <h3>Organization</h3>
    <hr>
    <p>
      <a href="{{ client.website }}">{{ client.company }}</a><br>
      {{ client.street }}<br>
      {{ client.city }}, {{ client.state }} {{ client.postal_code }}</li>
    </p>

  </div>

  <div class="col-lg-4 col-sm-4">

    <h3>Invoices</h3>
    <hr>
    {% if invoices %}
      <table class="table">
        <thead>
          <tr>
            <th>Invoice #</th>
            <th>Paid</th>
            <th>Total Price</th>
          <tr>
        </thead>
        <tbody>
          {% for invoice in invoices %}
            <tr>
              <th><a href="{{ url_for('invoice.edit_invoice', invoice_id = invoice.id) }}">{{ invoice.invoice_number }}</a></th>
              <th>{{ invoice.paid }}</th>
              <th>${{ '{0:0.2f}'.format(invoice.total_price) }}</th>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>You haven't created any invoices for this client yet.</p>
    {% endif %}

  </div>

{% endblock content %}